logs:
  - name: root
    level: info
    formatter: "%d%T[%p]%T%m%n"
    appender:
      - type: FileLogAppender
        file: root.txt
      - type: StuoutAppender
        formatter: "%d%T%m%n"
  - name: system
    level: debug
    formatter: "%d%T%m%n"
    appender:
      - type: FileLogAppender
        file: system.txt
        formatter: "%d%T[%p]%T%m%n"
      - type: StuoutAppender